name: Mutation Testing with Stryker.NET
run-name: Mutation Testing with Stryker.NET
permissions:
  contents: read
on:
    push:
    schedule:
      - cron: "0 4 * * SUN"
jobs:
  dotnet-stryker-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Run Stryker.NET
        uses: lyndychivs/dotnet-stryker-action@v2
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
        with:
          configFile: "stryker-config.json"
          strykerArgs: "--reporter progress --reporter html --reporter dashboard --reporter json --version ${{ github.ref_name }}"
